import { router, useLocalSearchParams } from 'expo-router';
import * as ImagePicker from 'expo-image-picker';
import { useState } from 'react';
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { PrimaryButton } from '@/src/components/ui';
import { scanCards, ScanMatch, scannerConfigured } from '@/src/services/scanner';
import { useAppStore } from '@/src/store/AppStore';
import { colors, spacing } from '@/src/theme';

export default function DeckScanScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { decks, session, addCardToDeck } = useAppStore(); const deck = decks.find((item) => item.id === id); const [imageUri, setImageUri] = useState<string | null>(null); const [imageBase64, setImageBase64] = useState<string | null>(null); const [matches, setMatches] = useState<ScanMatch[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  if (!deck) return null;
  const pick = async (camera: boolean) => { setError(''); const permission = camera ? await ImagePicker.requestCameraPermissionsAsync() : await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) { setError(camera ? 'Permita o acesso à câmera.' : 'Permita o acesso às fotos.'); return; } const options: ImagePicker.ImagePickerOptions = { mediaTypes: ['images'], allowsEditing: false, quality: 0.7, base64: true }; const result = camera ? await ImagePicker.launchCameraAsync(options) : await ImagePicker.launchImageLibraryAsync(options); if (!result.canceled) { setImageUri(result.assets[0].uri); setImageBase64(result.assets[0].base64 ?? null); setMatches([]); } };
  const analyze = async () => { if (!imageBase64) return; setLoading(true); setError(''); try { const result = await scanCards(deck.tcgId, imageBase64, session?.accessToken); setMatches(result); if (!result.length) setError('Nenhuma carta foi identificada. Tente outra foto com boa luz e sem sobreposição.'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Scanner indisponível. Tente novamente.'); } finally { setLoading(false); } };
  const toggle = (index: number) => setMatches((items) => items.map((item, i) => i === index ? { ...item, selected: !item.selected } : item));
  const add = () => { matches.filter((item) => item.selected && item.card).forEach((item) => addCardToDeck(deck.id, item.card!, item.quantity)); router.back(); };
  return <SafeAreaView edges={['bottom']} style={styles.safe}><ScrollView contentContainerStyle={styles.container}>
    <Text style={styles.title}>Digitalizar cartas</Text><Text style={styles.description}>Espalhe até 10 cartas sem sobreposição, use boa iluminação e fotografe de cima.</Text>
    {!scannerConfigured && <View style={styles.notice}><Text style={styles.noticeTitle}>Scanner aguardando configuração</Text><Text style={styles.noticeText}>A câmera e a revisão estão prontas. Para reconhecer as cartas automaticamente, publique a função de visão no Supabase e configure a URL.</Text></View>}
    <View style={styles.actions}><PrimaryButton label="Abrir câmera" onPress={() => pick(true)} /><PrimaryButton secondary label="Escolher foto" onPress={() => pick(false)} /></View>
    {imageUri && <><Image source={{ uri: imageUri }} resizeMode="contain" style={styles.preview} /><PrimaryButton label={loading ? 'Analisando...' : 'Identificar até 10 cartas'} onPress={analyze} /></>}{!!error && <Text style={styles.error}>{error}</Text>}
    {loading && <ActivityIndicator color={colors.primary} size="large" />}{matches.length > 0 && <><Text style={styles.section}>Revise as identificações</Text><View style={styles.list}>{matches.map((item, index) => <Pressable key={`${item.detection.name}-${index}`} onPress={() => toggle(index)} style={[styles.match, item.selected && styles.matchSelected]}><Text style={styles.check}>{item.selected ? '✓' : '○'}</Text><View style={{ flex: 1 }}><Text style={styles.cardName}>{item.card?.name ?? item.detection.name}</Text><Text style={styles.cardMeta}>{item.card ? `${item.card.set} · #${item.card.number}` : 'Não encontrada no catálogo'}{item.detection.confidence != null ? ` · ${Math.round(item.detection.confidence * 100)}%` : ''}</Text></View><Text style={styles.quantity}>{item.quantity}×</Text></Pressable>)}</View><PrimaryButton label="Adicionar selecionadas ao deck" onPress={add} /></>}
  </ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, container: { padding: spacing.lg, paddingBottom: 48, gap: 14 }, title: { color: colors.text, fontSize: 28, fontWeight: '900' }, description: { color: colors.muted, lineHeight: 21 }, notice: { backgroundColor: colors.surfaceAlt, borderColor: colors.border, borderWidth: 1, borderRadius: 14, padding: 14 }, noticeTitle: { color: colors.text, fontWeight: '900' }, noticeText: { color: colors.muted, lineHeight: 19, marginTop: 5, fontSize: 12 }, actions: { gap: 9 }, preview: { width: '100%', height: 280, borderRadius: 16, backgroundColor: colors.surface }, error: { color: colors.danger, backgroundColor: colors.surface, borderRadius: 12, padding: 12, lineHeight: 19 }, section: { color: colors.text, fontSize: 18, fontWeight: '900', marginTop: spacing.md }, list: { gap: 8 }, match: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 13, padding: 12 }, matchSelected: { borderColor: colors.primary }, check: { color: colors.primary, fontSize: 22 }, cardName: { color: colors.text, fontWeight: '900' }, cardMeta: { color: colors.muted, fontSize: 11, marginTop: 3 }, quantity: { color: colors.text, fontWeight: '900' } });
