import AsyncStorage from '@react-native-async-storage/async-storage';
import { createContext, PropsWithChildren, useContext, useEffect, useMemo, useRef, useState } from 'react';
import { Card, CollectionItem, Deck, DeckFormat, Language, Region, TcgId } from '@/src/types';
import { defaultFormat } from '@/src/services/deckRules';
import { hydrateCatalog } from '@/src/services/catalog';
import { BackupPayload, CloudSession, isCloudConfigured, pullBackup, pushBackup, refreshSession, saveUsername as cloudSaveUsername, signIn as cloudSignIn, signUp as cloudSignUp } from '@/src/services/cloud';

type CollectionDraft = Omit<CollectionItem, 'id'>;
type SyncState = 'idle' | 'syncing' | 'synced' | 'error';
type AppState = {
  selectedTcg: TcgId | null; language: Language; region: Region; collection: CollectionItem[]; wishlist: string[]; savedCards: Card[]; decks: Deck[];
  session: CloudSession | null; cloudConfigured: boolean; syncState: SyncState; syncError: string | null; lastSyncedAt: string | null; autoSyncEnabled: boolean;
  selectTcg: (id: TcgId) => void; setLanguage: (value: Language) => void; setRegion: (value: Region) => void;
  addCollectionItem: (draft: CollectionDraft) => void; updateCollectionItem: (id: string, draft: CollectionDraft) => void; removeCollectionItem: (id: string) => void; toggleWishlist: (card: Card) => void;
  createDeck: (tcgId: TcgId, name: string) => string; renameDeck: (id: string, name: string) => void; setDeckFormat: (id: string, format: DeckFormat) => void; removeDeck: (id: string) => void; addCardToDeck: (deckId: string, card: Card, quantity?: number) => void; setDeckCardQuantity: (deckId: string, cardId: string, quantity: number) => void;
  signIn: (email: string, password: string) => Promise<void>; signUp: (email: string, password: string, username: string) => Promise<'signed-in' | 'confirmation-required'>; setUsername: (username: string) => Promise<void>; signOut: () => void; backupNow: () => Promise<void>; restoreBackup: () => Promise<boolean>;
};
const Store = createContext<AppState | null>(null); const STORAGE_KEY = '@tcg-hub/state'; const SESSION_KEY = '@tcg-hub/session';

export function AppStoreProvider({ children }: PropsWithChildren) {
  const [selectedTcg, selectTcg] = useState<TcgId | null>(null); const [language, setLanguage] = useState<Language>('pt'); const [region, setRegion] = useState<Region>('BR'); const [collection, setCollection] = useState<CollectionItem[]>([]); const [wishlist, setWishlist] = useState<string[]>([]); const [savedCards, setSavedCards] = useState<Card[]>([]); const [decks, setDecks] = useState<Deck[]>([]); const [ready, setReady] = useState(false);
  const [session, setSession] = useState<CloudSession | null>(null); const [syncState, setSyncState] = useState<SyncState>('idle'); const [syncError, setSyncError] = useState<string | null>(null); const [lastSyncedAt, setLastSyncedAt] = useState<string | null>(null); const [autoSyncEnabled, setAutoSyncEnabled] = useState(false); const autoSyncTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => { Promise.all([AsyncStorage.getItem(STORAGE_KEY), AsyncStorage.getItem(SESSION_KEY)]).then(async ([rawState, rawSession]) => { if (rawState) applyPayload(JSON.parse(rawState)); if (rawSession && isCloudConfigured) { try { const stored = JSON.parse(rawSession) as CloudSession; const renewed = await refreshSession(stored.refreshToken); setSession(renewed); setAutoSyncEnabled(true); } catch { await AsyncStorage.removeItem(SESSION_KEY); } } }).finally(() => setReady(true)); }, []);
  const payload = useMemo<BackupPayload>(() => ({ selectedTcg, language, region, collection, wishlist, savedCards, decks, schemaVersion: 2 }), [selectedTcg, language, region, collection, wishlist, savedCards, decks]);
  useEffect(() => { if (ready) AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(payload)); }, [ready, payload]);
  useEffect(() => { if (!ready) return; if (session) AsyncStorage.setItem(SESSION_KEY, JSON.stringify(session)); else AsyncStorage.removeItem(SESSION_KEY); }, [ready, session]);
  useEffect(() => { if (!session) return; const delay = Math.max(1000, session.expiresAt - Date.now() - 60000); const timer = setTimeout(() => refreshSession(session.refreshToken).then(setSession).catch(() => { setSession(null); setAutoSyncEnabled(false); setSyncError('Sua sessão expirou. Entre novamente.'); }), delay); return () => clearTimeout(timer); }, [session]);
  useEffect(() => { if (!ready || !session || !autoSyncEnabled) return; if (autoSyncTimer.current) clearTimeout(autoSyncTimer.current); autoSyncTimer.current = setTimeout(() => performBackup(session, payload), 1800); return () => { if (autoSyncTimer.current) clearTimeout(autoSyncTimer.current); }; }, [ready, session, autoSyncEnabled, payload]);

  function applyPayload(saved: Partial<BackupPayload> & { collection?: Array<string | CollectionItem> }) { selectTcg(saved.selectedTcg ?? null); setLanguage(saved.language ?? 'pt'); setRegion(saved.region ?? 'BR'); const migrated = (saved.collection ?? []).map((item, index) => typeof item === 'string' ? { id: `migrated-${item}-${index}`, cardId: item, quantity: 1, condition: 'NM' as const, language: 'EN' as const, foil: false, purchasePrice: null } : item); const restoredCards = saved.savedCards ?? []; const restoredDecks = (saved.decks ?? []).map((deck) => ({ ...deck, format: deck.format ?? defaultFormat(deck.tcgId) })); hydrateCatalog([...migrated, ...restoredCards.map((card) => ({ cardSnapshot: card })), ...restoredDecks.flatMap((deck) => deck.cards)]); setCollection(migrated); setWishlist(saved.wishlist ?? []); setSavedCards(restoredCards); setDecks(restoredDecks); }
  async function performBackup(activeSession = session, activePayload = payload) { if (!activeSession) throw new Error('Entre em sua conta para sincronizar.'); setSyncState('syncing'); setSyncError(null); try { await pushBackup(activeSession, activePayload); setLastSyncedAt(new Date().toISOString()); setSyncState('synced'); setAutoSyncEnabled(true); } catch (error) { const message = error instanceof Error ? error.message : 'Falha na sincronização.'; setSyncError(message); setSyncState('error'); throw error; } }
  async function login(email: string, password: string) { setSyncError(null); const nextSession = await cloudSignIn(email.trim(), password); setSession(nextSession); setSyncState('idle'); setAutoSyncEnabled(false); }
  async function register(email: string, password: string, username: string) { setSyncError(null); try { const nextSession = await cloudSignUp(email.trim(), password, username); if (nextSession) { setSession(nextSession); setAutoSyncEnabled(false); return 'signed-in' as const; } return 'confirmation-required' as const; } catch (error) { if (error instanceof Error && /database|duplicate|unique/i.test(error.message)) throw new Error('Este nome de usuário já está em uso.'); throw error; } }
  async function updateUsername(username: string) { if (!session) throw new Error('Entre em sua conta para definir um usuário.'); try { setSession(await cloudSaveUsername(session, username)); } catch (error) { if (error instanceof Error && /duplicate|unique/i.test(error.message)) throw new Error('Este nome de usuário já está em uso.'); throw error; } }
  async function restore() { if (!session) throw new Error('Entre em sua conta para restaurar.'); setSyncState('syncing'); setSyncError(null); try { const backup = await pullBackup(session); if (!backup) { setSyncState('idle'); return false; } applyPayload(backup.payload); setLastSyncedAt(backup.updated_at); setSyncState('synced'); setAutoSyncEnabled(true); return true; } catch (error) { const message = error instanceof Error ? error.message : 'Falha ao restaurar.'; setSyncError(message); setSyncState('error'); throw error; } }

  const value = useMemo<AppState>(() => ({ selectedTcg, language, region, collection, wishlist, savedCards, decks, session, cloudConfigured: isCloudConfigured, syncState, syncError, lastSyncedAt, autoSyncEnabled, selectTcg, setLanguage, setRegion,
    addCollectionItem: (draft) => setCollection((items) => [...items, { ...draft, id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}` }]), updateCollectionItem: (id, draft) => setCollection((items) => items.map((item) => item.id === id ? { ...draft, id } : item)), removeCollectionItem: (id) => setCollection((items) => items.filter((item) => item.id !== id)), toggleWishlist: (card) => { setWishlist((items) => items.includes(card.id) ? items.filter((item) => item !== card.id) : [...items, card.id]); setSavedCards((items) => items.some((item) => item.id === card.id) ? items : [...items, card]); },
    createDeck: (tcgId, name) => { const id = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`; const now = new Date().toISOString(); setDecks((items) => [...items, { id, tcgId, name: name.trim(), format: defaultFormat(tcgId), cards: [], createdAt: now, updatedAt: now }]); return id; }, renameDeck: (id, name) => setDecks((items) => items.map((deck) => deck.id === id ? { ...deck, name: name.trim(), updatedAt: new Date().toISOString() } : deck)), setDeckFormat: (id, format) => setDecks((items) => items.map((deck) => deck.id === id ? { ...deck, format, updatedAt: new Date().toISOString() } : deck)), removeDeck: (id) => setDecks((items) => items.filter((deck) => deck.id !== id)), addCardToDeck: (deckId, card, quantity = 1) => setDecks((items) => items.map((deck) => { if (deck.id !== deckId || deck.tcgId !== card.tcgId) return deck; const existing = deck.cards.find((item) => item.cardId === card.id); const cards = existing ? deck.cards.map((item) => item.cardId === card.id ? { ...item, quantity: item.quantity + quantity, cardSnapshot: card } : item) : [...deck.cards, { cardId: card.id, quantity, cardSnapshot: card }]; return { ...deck, cards, updatedAt: new Date().toISOString() }; })), setDeckCardQuantity: (deckId, cardId, quantity) => setDecks((items) => items.map((deck) => deck.id !== deckId ? deck : { ...deck, cards: quantity <= 0 ? deck.cards.filter((item) => item.cardId !== cardId) : deck.cards.map((item) => item.cardId === cardId ? { ...item, quantity } : item), updatedAt: new Date().toISOString() })),
    signIn: login, signUp: register, setUsername: updateUsername, signOut: () => { setSession(null); setAutoSyncEnabled(false); setSyncState('idle'); setSyncError(null); AsyncStorage.removeItem(SESSION_KEY); }, backupNow: () => performBackup(), restoreBackup: restore,
  }), [selectedTcg, language, region, collection, wishlist, savedCards, decks, session, syncState, syncError, lastSyncedAt, autoSyncEnabled, payload]);
  return <Store.Provider value={value}>{children}</Store.Provider>;
}
export function useAppStore() { const value = useContext(Store); if (!value) throw new Error('useAppStore must be inside AppStoreProvider'); return value; }
