import AsyncStorage from '@react-native-async-storage/async-storage'; import { createContext, PropsWithChildren, useContext, useEffect, useMemo, useState } from 'react'; import { CollectionItem, Language, Region, TcgId } from '@/src/types';
type CollectionDraft = Omit<CollectionItem, 'id'>;
type AppState = { selectedTcg: TcgId | null; language: Language; region: Region; collection: CollectionItem[]; wishlist: string[]; selectTcg: (id: TcgId) => void; setLanguage: (value: Language) => void; setRegion: (value: Region) => void; addCollectionItem: (draft: CollectionDraft) => void; updateCollectionItem: (id: string, draft: CollectionDraft) => void; removeCollectionItem: (id: string) => void; toggleWishlist: (id: string) => void };
const Store = createContext<AppState | null>(null); const STORAGE_KEY = '@tcg-hub/state';
export function AppStoreProvider({ children }: PropsWithChildren) { const [selectedTcg, selectTcg] = useState<TcgId | null>(null); const [language, setLanguage] = useState<Language>('pt'); const [region, setRegion] = useState<Region>('BR'); const [collection, setCollection] = useState<CollectionItem[]>([]); const [wishlist, setWishlist] = useState<string[]>([]); const [ready, setReady] = useState(false);
  useEffect(() => { AsyncStorage.getItem(STORAGE_KEY).then((raw) => { if (raw) { const saved = JSON.parse(raw); selectTcg(saved.selectedTcg ?? null); setLanguage(saved.language ?? 'pt'); setRegion(saved.region ?? 'BR'); const migrated = (saved.collection ?? []).map((item: string | CollectionItem, index: number) => typeof item === 'string' ? { id: `migrated-${item}-${index}`, cardId: item, quantity: 1, condition: 'NM', language: 'EN', foil: false, purchasePrice: null } : item); setCollection(migrated); setWishlist(saved.wishlist ?? []); } }).finally(() => setReady(true)); }, []);
  useEffect(() => { if (ready) AsyncStorage.setItem(STORAGE_KEY, JSON.stringify({ selectedTcg, language, region, collection, wishlist })); }, [ready, selectedTcg, language, region, collection, wishlist]);
  const value = useMemo(() => ({ selectedTcg, language, region, collection, wishlist, selectTcg, setLanguage, setRegion, addCollectionItem: (draft: CollectionDraft) => setCollection((items) => [...items, { ...draft, id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}` }]), updateCollectionItem: (id: string, draft: CollectionDraft) => setCollection((items) => items.map((item) => item.id === id ? { ...draft, id } : item)), removeCollectionItem: (id: string) => setCollection((items) => items.filter((item) => item.id !== id)), toggleWishlist: (id: string) => setWishlist((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id]) }), [selectedTcg, language, region, collection, wishlist]); return <Store.Provider value={value}>{children}</Store.Provider>; }
export function useAppStore() { const value = useContext(Store); if (!value) throw new Error('useAppStore must be inside AppStoreProvider'); return value; }
