import { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Panel, PrimaryButton } from '@/src/components/ui';
import { useAppStore } from '@/src/store/AppStore';
import { colors, spacing } from '@/src/theme';

export default function AccountScreen() {
  const { session, cloudConfigured, syncState, syncError, lastSyncedAt, autoSyncEnabled, collection, wishlist, signIn, signUp, signOut, backupNow, restoreBackup } = useAppStore();
  const [mode, setMode] = useState<'login' | 'register'>('login'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const copies = collection.reduce((sum, item) => sum + item.quantity, 0);
  const execute = async (action: () => Promise<void>) => { setBusy(true); try { await action(); } catch (error) { Alert.alert('Não foi possível concluir', error instanceof Error ? error.message : 'Tente novamente.'); } finally { setBusy(false); } };
  const authenticate = () => execute(async () => { if (!email.includes('@') || password.length < 6) throw new Error('Informe um e-mail válido e uma senha com pelo menos 6 caracteres.'); if (mode === 'login') await signIn(email, password); else { const result = await signUp(email, password); if (result === 'confirmation-required') Alert.alert('Confirme seu e-mail', 'Enviamos uma mensagem de confirmação. Depois, volte e faça login.'); } });
  const confirmRestore = () => Alert.alert('Restaurar backup?', 'Os dados locais serão substituídos pelos dados salvos na nuvem.', [{ text: 'Cancelar', style: 'cancel' }, { text: 'Restaurar', onPress: () => execute(async () => { const found = await restoreBackup(); Alert.alert(found ? 'Backup restaurado' : 'Nenhum backup encontrado', found ? 'Sua coleção foi atualizada.' : 'Você pode enviar os dados deste aparelho para criar o primeiro backup.'); }) }]);
  if (!cloudConfigured) return <SafeAreaView edges={['bottom']} style={styles.safe}><View style={styles.center}><Text style={styles.icon}>☁</Text><Text style={styles.title}>Nuvem pronta para configurar</Text><Text style={styles.description}>O aplicativo continua funcionando como visitante. Para ativar contas, configure o projeto Supabase seguindo o README e o arquivo `.env.example`.</Text></View></SafeAreaView>;
  if (!session) return <SafeAreaView edges={['bottom']} style={styles.safe}><ScrollView contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled"><Text style={styles.title}>{mode === 'login' ? 'Entrar na sua conta' : 'Criar uma conta'}</Text><Text style={styles.description}>Sincronize sua coleção e wishlist entre dispositivos.</Text><Text style={styles.label}>E-mail</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="voce@email.com" placeholderTextColor={colors.muted} style={styles.input} /><Text style={styles.label}>Senha</Text><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="Mínimo de 6 caracteres" placeholderTextColor={colors.muted} style={styles.input} /><View style={styles.actions}><PrimaryButton label={busy ? 'Aguarde...' : mode === 'login' ? 'Entrar' : 'Criar conta'} onPress={authenticate} /><Pressable onPress={() => setMode(mode === 'login' ? 'register' : 'login')}><Text style={styles.switch}>{mode === 'login' ? 'Ainda não tenho conta' : 'Já tenho uma conta'}</Text></Pressable></View><Text style={styles.security}>Sua sessão será renovada automaticamente neste dispositivo até você escolher sair.</Text></ScrollView></SafeAreaView>;
  return <SafeAreaView edges={['bottom']} style={styles.safe}><ScrollView contentContainerStyle={styles.container}><Text style={styles.eyebrow}>CONECTADO</Text><Text style={styles.title}>{session.user.email}</Text><Panel style={styles.stats}><View><Text style={styles.statNumber}>{copies}</Text><Text style={styles.statLabel}>cartas</Text></View><View><Text style={styles.statNumber}>{wishlist.length}</Text><Text style={styles.statLabel}>wishlist</Text></View></Panel><Panel style={styles.syncPanel}><Text style={styles.syncTitle}>{syncState === 'syncing' ? 'Sincronizando...' : syncState === 'error' ? 'Erro na sincronização' : autoSyncEnabled ? 'Backup automático ativo' : 'Escolha o primeiro backup'}</Text><Text style={styles.description}>{syncError ?? (lastSyncedAt ? `Última sincronização: ${new Date(lastSyncedAt).toLocaleString('pt-BR')}` : 'Envie os dados deste aparelho ou restaure um backup existente.')}</Text></Panel><View style={styles.actions}><PrimaryButton label={busy ? 'Aguarde...' : 'Enviar backup agora'} onPress={() => execute(backupNow)} /><PrimaryButton secondary label="Restaurar da nuvem" onPress={confirmRestore} /><Pressable onPress={signOut}><Text style={styles.signOut}>Sair da conta</Text></Pressable></View></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, container: { padding: spacing.lg, paddingBottom: 48 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: spacing.xl }, icon: { color: colors.primary, fontSize: 64 }, title: { color: colors.text, fontSize: 28, fontWeight: '900', marginTop: spacing.md }, eyebrow: { color: colors.primary, fontSize: 12, fontWeight: '900', letterSpacing: 2 }, description: { color: colors.muted, lineHeight: 21, marginTop: spacing.sm }, label: { color: colors.text, fontWeight: '800', marginTop: spacing.lg, marginBottom: spacing.sm }, input: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 14, color: colors.text, paddingHorizontal: 15, paddingVertical: 13, fontSize: 16 }, actions: { gap: 13, marginTop: spacing.xl }, switch: { color: colors.accent, textAlign: 'center', fontWeight: '800', padding: 8 }, security: { color: colors.muted, fontSize: 11, lineHeight: 17, marginTop: spacing.xl, textAlign: 'center' }, stats: { flexDirection: 'row', justifyContent: 'space-around', marginTop: spacing.lg }, statNumber: { color: colors.primary, fontSize: 28, fontWeight: '900', textAlign: 'center' }, statLabel: { color: colors.muted, marginTop: 3 }, syncPanel: { marginTop: spacing.md }, syncTitle: { color: colors.text, fontWeight: '900', fontSize: 17 }, signOut: { color: colors.danger, textAlign: 'center', fontWeight: '800', padding: 10 } });
