import { router, useLocalSearchParams } from 'expo-router';
import { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { CardTile } from '@/src/components/CardTile';
import { Pill, SearchInput } from '@/src/components/ui';
import { cards, findTcg } from '@/src/data/catalog';
import { useAppStore } from '@/src/store/AppStore';
import { colors, spacing } from '@/src/theme';

type Tab = 'collection' | 'wishlist';
export default function CollectionScreen() {
  const { tcgId } = useLocalSearchParams<{ tcgId: string }>(); const { collection, wishlist, region, language } = useAppStore();
  const [tab, setTab] = useState<Tab>('collection'); const [query, setQuery] = useState(''); const [condition, setCondition] = useState('Todas');
  const tcg = findTcg(tcgId); const tcgItems = collection.filter((entry) => cards.some((card) => card.id === entry.cardId && card.tcgId === tcgId));
  const totalCopies = tcgItems.reduce((sum, entry) => sum + entry.quantity, 0); const marketValue = tcgItems.reduce((sum, entry) => { const card = cards.find((item) => item.id === entry.cardId); return sum + (card ? (region === 'BR' ? card.priceBRL : card.priceUSD) * entry.quantity : 0); }, 0); const invested = tcgItems.reduce((sum, entry) => sum + (entry.purchasePrice ?? 0) * entry.quantity, 0);
  const filteredEntries = useMemo(() => tcgItems.filter((entry) => { const card = cards.find((item) => item.id === entry.cardId); return card && (condition === 'Todas' || entry.condition === condition) && `${card.name} ${card.set} ${entry.language}`.toLowerCase().includes(query.toLowerCase()); }), [tcgItems, condition, query]);
  const wishlistCards = cards.filter((card) => card.tcgId === tcgId && wishlist.includes(card.id) && `${card.name} ${card.set}`.toLowerCase().includes(query.toLowerCase()));
  const money = (value: number) => region === 'BR' ? `R$ ${value.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}` : `$${value.toLocaleString('en-US', { minimumFractionDigits: 2 })}`;
  return <SafeAreaView edges={['bottom']} style={styles.safe}><ScrollView contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled">
    <Text style={styles.eyebrow}>{tcg?.name}</Text><Text style={styles.title}>{language === 'pt' ? 'Minha coleção' : 'My collection'}</Text>
    <View style={styles.summary}><View><Text style={styles.summaryLabel}>Valor estimado</Text><Text style={styles.value}>{money(marketValue)}</Text><Text style={styles.invested}>Investido: {money(invested)}</Text></View><View style={styles.total}><Text style={styles.totalNumber}>{totalCopies}</Text><Text style={styles.summaryLabel}>cópias</Text><Text style={styles.entries}>{tcgItems.length} registro(s)</Text></View></View>
    <View style={styles.tabs}><Pressable onPress={() => { setTab('collection'); setCondition('Todas'); }} style={[styles.tab, tab === 'collection' && styles.tabActive]}><Text style={[styles.tabText, tab === 'collection' && styles.tabTextActive]}>Coleção ({totalCopies})</Text></Pressable><Pressable onPress={() => { setTab('wishlist'); setCondition('Todas'); }} style={[styles.tab, tab === 'wishlist' && styles.tabActive]}><Text style={[styles.tabText, tab === 'wishlist' && styles.tabTextActive]}>Wishlist ({wishlistCards.length})</Text></Pressable></View>
    <SearchInput value={query} onChangeText={setQuery} placeholder="Buscar nesta lista..." />
    {tab === 'collection' && tcgItems.length > 0 && <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{['Todas', 'NM', 'EX', 'GD', 'LP', 'PL'].map((item) => <Pill key={item} label={item} active={condition === item} onPress={() => setCondition(item)} />)}</ScrollView>}
    {tab === 'collection' ? (filteredEntries.length > 0 ? <View style={styles.list}>{filteredEntries.map((entry) => { const card = cards.find((item) => item.id === entry.cardId)!; return <Pressable key={entry.id} onPress={() => router.push({ pathname: '/collection-entry', params: { cardId: card.id, entryId: entry.id } })} style={styles.entry}><View style={[styles.thumb, { backgroundColor: card.imageColor }]}><Text style={styles.thumbText}>{card.name[0]}</Text></View><View style={styles.entryInfo}><Text style={styles.cardName}>{card.name}</Text><Text style={styles.cardMeta}>{card.set} · #{card.number}</Text><View style={styles.tags}><Text style={styles.tag}>{entry.condition}</Text><Text style={styles.tag}>{entry.language}</Text>{entry.foil && <Text style={[styles.tag, styles.foil]}>FOIL</Text>}</View><Text style={styles.purchase}>{entry.purchasePrice == null ? 'Preço de aquisição não informado' : `Aquisição: ${money(entry.purchasePrice)} cada`}</Text></View><View style={styles.quantity}><Text style={styles.quantityNumber}>{entry.quantity}×</Text><Text style={styles.edit}>Editar</Text></View></Pressable>; })}</View> : <EmptyState tcgId={tcgId} />) : (wishlistCards.length > 0 ? <View style={styles.grid}>{wishlistCards.map((card) => <CardTile key={card.id} card={card} />)}</View> : <EmptyState tcgId={tcgId} />)}
  </ScrollView></SafeAreaView>;
}
function EmptyState({ tcgId }: { tcgId: string }) { return <View style={styles.empty}><Text style={styles.emptyIcon}>▣</Text><Text style={styles.emptyTitle}>Nada por aqui ainda</Text><Text style={styles.emptyText}>Explore o catálogo e adicione suas primeiras cartas.</Text><Pressable onPress={() => router.push({ pathname: '/explore', params: { tcgId } })} style={styles.exploreButton}><Text style={styles.exploreButtonText}>Explorar cartas</Text></Pressable></View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, container: { padding: spacing.lg, paddingBottom: 48 }, eyebrow: { color: colors.accent, fontWeight: '800' }, title: { color: colors.text, fontSize: 30, fontWeight: '900', marginTop: 4, marginBottom: spacing.lg }, summary: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 20, padding: spacing.lg, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, summaryLabel: { color: colors.muted }, value: { color: colors.primary, fontSize: 25, fontWeight: '900', marginTop: 5 }, invested: { color: colors.accent, fontSize: 12, marginTop: 6 }, total: { alignItems: 'center' }, totalNumber: { color: colors.text, fontSize: 24, fontWeight: '900' }, entries: { color: colors.muted, fontSize: 11, marginTop: 4 }, tabs: { flexDirection: 'row', backgroundColor: colors.surface, borderRadius: 15, padding: 4, marginVertical: spacing.lg }, tab: { flex: 1, alignItems: 'center', padding: 11, borderRadius: 11 }, tabActive: { backgroundColor: colors.surfaceAlt }, tabText: { color: colors.muted, fontWeight: '800' }, tabTextActive: { color: colors.text }, filters: { gap: 8, paddingVertical: spacing.md }, list: { gap: 10, marginTop: spacing.md }, entry: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 16, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 12 }, thumb: { width: 54, height: 72, borderRadius: 9, alignItems: 'center', justifyContent: 'center' }, thumbText: { color: '#FFFFFFCC', fontSize: 28, fontWeight: '900' }, entryInfo: { flex: 1 }, cardName: { color: colors.text, fontWeight: '900' }, cardMeta: { color: colors.muted, fontSize: 11, marginTop: 3 }, tags: { flexDirection: 'row', gap: 5, marginTop: 7 }, tag: { color: colors.accent, backgroundColor: colors.surfaceAlt, borderRadius: 6, paddingHorizontal: 7, paddingVertical: 3, fontSize: 10, fontWeight: '900' }, foil: { color: colors.primary }, purchase: { color: colors.muted, fontSize: 10, marginTop: 7 }, quantity: { alignItems: 'center' }, quantityNumber: { color: colors.primary, fontSize: 20, fontWeight: '900' }, edit: { color: colors.muted, fontSize: 10, marginTop: 6 }, grid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', marginTop: spacing.md }, empty: { alignItems: 'center', paddingVertical: 54 }, emptyIcon: { color: colors.primary, fontSize: 54 }, emptyTitle: { color: colors.text, fontSize: 21, fontWeight: '900', marginTop: spacing.md }, emptyText: { color: colors.muted, textAlign: 'center', lineHeight: 21, marginTop: spacing.sm }, exploreButton: { backgroundColor: colors.primary, borderRadius: 14, paddingHorizontal: spacing.lg, paddingVertical: 13, marginTop: spacing.lg }, exploreButtonText: { color: colors.background, fontWeight: '900' } });
