import { router, useLocalSearchParams } from 'expo-router';
import { useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Pill, PrimaryButton, SearchInput } from '@/src/components/ui';
import { cards as localCards, findTcg } from '@/src/data/catalog';
import { getCachedCard, searchCatalog } from '@/src/services/catalog';
import { useAppStore } from '@/src/store/AppStore';
import { colors, pressFeedback, spacing } from '@/src/theme';
import { Card, TcgId } from '@/src/types';

type Tab = 'collection' | 'wishlist'; type Sort = 'value' | 'name' | 'gain';
export default function MarketScreen() {
  const { tcgId } = useLocalSearchParams<{ tcgId: TcgId }>(); const { collection, wishlist, savedCards, region } = useAppStore(); const [tab, setTab] = useState<Tab>('collection'); const [sort, setSort] = useState<Sort>('value'); const [query, setQuery] = useState(''); const [refreshing, setRefreshing] = useState(false); const [lastUpdatedAt, setLastUpdatedAt] = useState<string | null>(null); const [notice, setNotice] = useState(''); const [priceOverrides, setPriceOverrides] = useState<Record<string, Card>>({}); const tcg = findTcg(tcgId);
  const money = (value: number) => region === 'BR' ? `R$ ${value.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : `$${value.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; const priceOf = (card: Card) => region === 'BR' ? card.priceBRL : card.priceUSD;
  const rows = useMemo(() => collection.map((entry) => { const card = priceOverrides[entry.cardId] ?? getCachedCard(entry.cardId) ?? entry.cardSnapshot; if (!card || card.tcgId !== tcgId) return null; const market = priceOf(card) * entry.quantity; const invested = (entry.purchasePrice ?? 0) * entry.quantity; return { entry, card, market, invested, gain: entry.purchasePrice == null ? null : market - invested }; }).filter((item): item is NonNullable<typeof item> => Boolean(item)), [collection, tcgId, region, priceOverrides]);
  const wishlistCards = useMemo(() => [...localCards, ...savedCards.filter((saved) => !localCards.some((card) => card.id === saved.id))].filter((card) => card.tcgId === tcgId && wishlist.includes(card.id)).map((card) => priceOverrides[card.id] ?? card), [wishlist, savedCards, tcgId, priceOverrides]);
  const totalMarket = rows.reduce((sum, item) => sum + item.market, 0); const investedRows = rows.filter((item) => item.entry.purchasePrice != null); const totalInvested = investedRows.reduce((sum, item) => sum + item.invested, 0); const comparisonMarket = investedRows.reduce((sum, item) => sum + item.market, 0); const gain = comparisonMarket - totalInvested; const wishlistCost = wishlistCards.reduce((sum, card) => sum + priceOf(card), 0);
  const visibleRows = [...rows].filter((item) => `${item.card.name} ${item.card.set}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => sort === 'name' ? a.card.name.localeCompare(b.card.name) : sort === 'gain' ? (b.gain ?? -Infinity) - (a.gain ?? -Infinity) : b.market - a.market); const visibleWishlist = wishlistCards.filter((card) => `${card.name} ${card.set}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => sort === 'name' ? a.name.localeCompare(b.name) : priceOf(b) - priceOf(a));
  const refresh = async () => { setRefreshing(true); setNotice(''); try { const targets = [...new Map([...rows.map((item) => item.card), ...wishlistCards].map((card) => [card.id, card])).values()]; if (!targets.length) { setNotice('Adicione cartas à coleção ou wishlist para acompanhar preços.'); return; } let online = false; const updates: Record<string, Card> = {}; for (const card of targets.slice(0, 20)) { const result = await searchCatalog(tcgId, card.name); online ||= result.source !== 'local'; const match = result.cards.find((item) => item.externalId === card.externalId) ?? result.cards.find((item) => item.name.toLowerCase() === card.name.toLowerCase() && item.number === card.number) ?? result.cards.find((item) => item.name.toLowerCase() === card.name.toLowerCase()); if (match) updates[card.id] = { ...match, id: card.id }; } setPriceOverrides((current) => ({ ...current, ...updates })); setLastUpdatedAt(new Date().toISOString()); setNotice(online ? `${Object.keys(updates).length} preço(s) atualizado(s) pelos catálogos disponíveis.` : 'Ainda não há uma fonte online de preços para este TCG.'); } finally { setRefreshing(false); } };
  const source = tcgId === 'magic' ? 'Scryfall' : tcgId === 'pokemon' ? 'Pokémon TCG API' : tcgId === 'riftbound' ? 'Aguardando fonte confiável' : 'Catálogo demonstrativo';
  return <SafeAreaView edges={['bottom']} style={styles.safe}><ScrollView contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled">
    <Text style={styles.eyebrow}>{tcg?.name}</Text><Text style={styles.title}>Mercado</Text><Text style={styles.description}>Acompanhe estimativas da coleção e planeje sua wishlist.</Text>
    <View style={styles.summary}><View style={styles.heroValue}><Text style={styles.summaryLabel}>Valor estimado</Text><Text style={styles.marketValue}>{money(totalMarket)}</Text></View><View style={styles.summaryGrid}><View><Text style={styles.summaryLabel}>Investido informado</Text><Text style={styles.summaryNumber}>{money(totalInvested)}</Text></View><View><Text style={styles.summaryLabel}>Diferença comparável</Text><Text style={[styles.summaryNumber, gain >= 0 ? styles.positive : styles.negative]}>{gain >= 0 ? '+' : ''}{money(gain)}</Text></View></View></View>
    <View style={styles.source}><View style={{ flex: 1 }}><Text style={styles.sourceTitle}>Fonte: {source}</Text><Text style={styles.sourceText}>{lastUpdatedAt ? `Atualizado em ${new Date(lastUpdatedAt).toLocaleString('pt-BR')}` : 'Use o botão para consultar os valores mais recentes.'}</Text></View><PrimaryButton secondary label={refreshing ? 'Atualizando...' : 'Atualizar'} onPress={refresh} /></View>{refreshing && <ActivityIndicator color={colors.primary} />}{!!notice && <Text style={styles.notice}>{notice}</Text>}
    <View style={styles.tabs}><Pressable onPress={() => setTab('collection')} style={({ pressed }) => [styles.tab, tab === 'collection' && styles.tabActive, pressed && pressFeedback]}><Text style={[styles.tabText, tab === 'collection' && styles.tabTextActive]}>Coleção</Text></Pressable><Pressable onPress={() => setTab('wishlist')} style={({ pressed }) => [styles.tab, tab === 'wishlist' && styles.tabActive, pressed && pressFeedback]}><Text style={[styles.tabText, tab === 'wishlist' && styles.tabTextActive]}>Wishlist · {money(wishlistCost)}</Text></Pressable></View>
    <SearchInput value={query} onChangeText={setQuery} placeholder="Buscar carta..." /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}><Pill label="Maior valor" active={sort === 'value'} onPress={() => setSort('value')} /><Pill label="Nome" active={sort === 'name'} onPress={() => setSort('name')} />{tab === 'collection' && <Pill label="Maior ganho" active={sort === 'gain'} onPress={() => setSort('gain')} />}</ScrollView>
    {tab === 'collection' ? (visibleRows.length ? <View style={styles.list}>{visibleRows.map(({ entry, card, market, gain: itemGain }) => <Pressable key={entry.id} onPress={() => router.push({ pathname: '/card/[id]', params: { id: card.id } })} style={({ pressed }) => [styles.row, pressed && pressFeedback]}><View style={[styles.thumb, { backgroundColor: card.imageColor }]}><Text style={styles.thumbText}>{card.name[0]}</Text></View><View style={{ flex: 1 }}><Text style={styles.cardName}>{card.name}</Text><Text style={styles.cardMeta}>{entry.quantity}× · {card.set}</Text>{itemGain != null && <Text style={[styles.gain, itemGain >= 0 ? styles.positive : styles.negative]}>{itemGain >= 0 ? '+' : ''}{money(itemGain)} desde a aquisição</Text>}</View><Text style={styles.rowValue}>{money(market)}</Text></Pressable>)}</View> : <Empty text="Sua coleção ainda não possui cartas deste TCG." />) : (visibleWishlist.length ? <View style={styles.list}>{visibleWishlist.map((card) => <Pressable key={card.id} onPress={() => router.push({ pathname: '/card/[id]', params: { id: card.id } })} style={({ pressed }) => [styles.row, pressed && pressFeedback]}><View style={[styles.thumb, { backgroundColor: card.imageColor }]}><Text style={styles.thumbText}>{card.name[0]}</Text></View><View style={{ flex: 1 }}><Text style={styles.cardName}>{card.name}</Text><Text style={styles.cardMeta}>{card.set} · #{card.number}</Text></View><Text style={styles.rowValue}>{money(priceOf(card))}</Text></Pressable>)}</View> : <Empty text="Sua wishlist ainda está vazia para este TCG." />)}
    <Text style={styles.disclaimer}>Valores são estimativas dos catálogos internacionais, podem sofrer conversão cambial e não representam oferta de compra ou venda.</Text>
  </ScrollView></SafeAreaView>;
}
function Empty({ text }: { text: string }) { return <View style={styles.empty}><Text style={styles.emptyIcon}>◈</Text><Text style={styles.emptyText}>{text}</Text></View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, container: { padding: spacing.lg, paddingBottom: 48 }, eyebrow: { color: colors.accent, fontWeight: '900' }, title: { color: colors.text, fontSize: 30, fontWeight: '900', marginTop: 4 }, description: { color: colors.muted, marginTop: 6, lineHeight: 21 }, summary: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 20, padding: spacing.lg, marginTop: spacing.lg }, heroValue: { borderBottomColor: colors.border, borderBottomWidth: 1, paddingBottom: spacing.md }, summaryLabel: { color: colors.muted, fontSize: 11 }, marketValue: { color: colors.primary, fontWeight: '900', fontSize: 30, marginTop: 5 }, summaryGrid: { flexDirection: 'row', justifyContent: 'space-between', marginTop: spacing.md }, summaryNumber: { color: colors.text, fontWeight: '900', marginTop: 5 }, positive: { color: colors.primary }, negative: { color: colors.danger }, source: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: spacing.md }, sourceTitle: { color: colors.text, fontWeight: '800', fontSize: 12 }, sourceText: { color: colors.muted, fontSize: 10, marginTop: 3 }, notice: { color: colors.muted, backgroundColor: colors.surfaceAlt, borderRadius: 10, padding: 10, marginTop: 10, fontSize: 11 }, tabs: { flexDirection: 'row', backgroundColor: colors.surface, borderRadius: 15, padding: 4, marginTop: spacing.xl }, tab: { flex: 1, alignItems: 'center', padding: 11, borderRadius: 11 }, tabActive: { backgroundColor: colors.surfaceAlt }, tabText: { color: colors.muted, fontWeight: '800', fontSize: 12 }, tabTextActive: { color: colors.text }, filters: { gap: 8, paddingVertical: spacing.md }, list: { gap: 8 }, row: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 14, padding: 10 }, thumb: { width: 42, height: 56, borderRadius: 8, alignItems: 'center', justifyContent: 'center' }, thumbText: { color: '#FFFFFFCC', fontSize: 21, fontWeight: '900' }, cardName: { color: colors.text, fontWeight: '900' }, cardMeta: { color: colors.muted, fontSize: 11, marginTop: 3 }, gain: { fontSize: 10, marginTop: 5, fontWeight: '800' }, rowValue: { color: colors.primary, fontWeight: '900' }, empty: { alignItems: 'center', paddingVertical: 54 }, emptyIcon: { color: colors.primary, fontSize: 48 }, emptyText: { color: colors.muted, textAlign: 'center', marginTop: 10 }, disclaimer: { color: colors.muted, fontSize: 10, lineHeight: 16, textAlign: 'center', marginTop: spacing.xl } });
