import { router, useLocalSearchParams } from 'expo-router';
import { useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Panel, Pill, PrimaryButton, SearchInput } from '@/src/components/ui';
import { getCachedCard, searchCatalog } from '@/src/services/catalog';
import { formatsFor, validateDeck } from '@/src/services/deckRules';
import { useAppStore } from '@/src/store/AppStore';
import { colors, pressFeedback, spacing } from '@/src/theme';
import { Card } from '@/src/types';

export default function DeckScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { decks, addCardToDeck, setDeckCardQuantity, setDeckFormat, removeDeck } = useAppStore(); const deck = decks.find((item) => item.id === id); const [query, setQuery] = useState(''); const [results, setResults] = useState<Card[]>([]); const [loading, setLoading] = useState(false);
  const total = deck?.cards.reduce((sum, item) => sum + item.quantity, 0) ?? 0; const resolved = useMemo(() => deck?.cards.map((item) => ({ ...item, card: getCachedCard(item.cardId) ?? item.cardSnapshot })).filter((item) => item.card) ?? [], [deck]);
  if (!deck) return <SafeAreaView style={styles.safe}><View style={styles.center}><Text style={styles.empty}>Deck não encontrado.</Text></View></SafeAreaView>;
  const validation = validateDeck(deck, getCachedCard); const availableFormats = formatsFor(deck.tcgId);
  const search = async () => { setLoading(true); const response = await searchCatalog(deck.tcgId, query); setResults(response.cards); setLoading(false); };
  const destroy = () => { const action = () => { removeDeck(deck.id); router.back(); }; if (Platform.OS === 'web') { if (typeof window !== 'undefined' && window.confirm('Excluir este deck?')) action(); } else Alert.alert('Excluir deck?', 'Todas as cartas desta lista serão removidas.', [{ text: 'Cancelar', style: 'cancel' }, { text: 'Excluir', style: 'destructive', onPress: action }]); };
  return <SafeAreaView edges={['bottom']} style={styles.safe}><ScrollView contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled">
    <Text style={styles.title}>{deck.name}</Text><Text style={styles.meta}>{total} cartas · {deck.cards.length} diferentes</Text>
    <Text style={styles.section}>Formato</Text><View style={styles.formatRow}>{availableFormats.map((format) => <Pill key={format.id} label={format.label} active={deck.format === format.id} onPress={() => setDeckFormat(deck.id, format.id)} />)}</View>
    <Panel style={[styles.validation, validation.valid ? styles.validationOk : styles.validationPending]}><View style={styles.validationHeader}><Text style={[styles.validationStatus, validation.valid && styles.validationStatusOk]}>{validation.valid ? '✓ Deck válido' : 'Deck incompleto'}</Text><Text style={styles.validationCount}>{validation.rule.deckSize == null ? `${validation.total} cartas` : `${validation.total}/${validation.rule.deckSize}`}</Text></View>{validation.rule.deckSize != null && <View style={styles.progressTrack}><View style={[styles.progressFill, { width: `${validation.progress * 100}%` }]} /></View>}<Text style={styles.ruleNote}>{validation.rule.note}</Text>{validation.issues.slice(0, 4).map((issue) => <Text key={issue} style={styles.issue}>• {issue}</Text>)}{validation.issues.length > 4 && <Text style={styles.issue}>• Mais {validation.issues.length - 4} alerta(s)</Text>}</Panel>
    <Text style={styles.section}>Adicionar pelo catálogo</Text><View style={styles.searchRow}><SearchInput value={query} onChangeText={setQuery} onSubmitEditing={search} placeholder="Nome da carta" style={{ flex: 1 }} /><PrimaryButton label="Buscar" onPress={search} /></View>
    {loading ? <ActivityIndicator color={colors.primary} style={{ margin: 24 }} /> : results.length > 0 && <View style={styles.results}>{results.slice(0, 12).map((card) => <Pressable key={card.id} onPress={() => addCardToDeck(deck.id, card)} style={({ pressed }) => [styles.result, pressed && pressFeedback]}><View style={[styles.thumb, { backgroundColor: card.imageColor }]}><Text style={styles.thumbText}>{card.name[0]}</Text></View><View style={{ flex: 1 }}><Text style={styles.cardName}>{card.name}</Text><Text style={styles.cardMeta}>{card.set} · #{card.number}</Text></View><Text style={styles.add}>＋</Text></Pressable>)}</View>}
    <Text style={styles.section}>Lista do deck</Text>{resolved.length === 0 ? <Text style={styles.empty}>Busque cartas no catálogo para começar.</Text> : <View style={styles.results}>{resolved.map((item) => <View key={item.cardId} style={styles.result}><View style={[styles.thumb, { backgroundColor: item.card!.imageColor }]}><Text style={styles.thumbText}>{item.card!.name[0]}</Text></View><View style={{ flex: 1 }}><Text style={styles.cardName}>{item.card!.name}</Text><Text style={styles.cardMeta}>{item.card!.set}</Text></View><View style={styles.counter}><Pressable onPress={() => setDeckCardQuantity(deck.id, item.cardId, item.quantity - 1)} style={({ pressed }) => pressed && pressFeedback}><Text style={styles.counterButton}>−</Text></Pressable><Text style={styles.quantity}>{item.quantity}</Text><Pressable onPress={() => setDeckCardQuantity(deck.id, item.cardId, item.quantity + 1)} style={({ pressed }) => pressed && pressFeedback}><Text style={styles.counterButton}>＋</Text></Pressable></View></View>)}</View>}
    <Pressable onPress={destroy} style={({ pressed }) => pressed && pressFeedback}><Text style={styles.delete}>Excluir deck</Text></Pressable>
  </ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, container: { padding: spacing.lg, paddingBottom: 48, gap: 12 }, center: { flex: 1, justifyContent: 'center' }, title: { color: colors.text, fontSize: 28, fontWeight: '900' }, meta: { color: colors.muted, marginBottom: 8 }, section: { color: colors.text, fontSize: 18, fontWeight: '900', marginTop: spacing.lg }, formatRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, validation: { marginTop: 2 }, validationOk: { borderColor: colors.primary }, validationPending: { borderColor: colors.accent }, validationHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, validationStatus: { color: colors.accent, fontWeight: '900', fontSize: 16 }, validationStatusOk: { color: colors.primary }, validationCount: { color: colors.text, fontWeight: '900' }, progressTrack: { height: 7, backgroundColor: colors.surfaceAlt, borderRadius: 99, overflow: 'hidden', marginTop: 12 }, progressFill: { height: '100%', backgroundColor: colors.primary, borderRadius: 99 }, ruleNote: { color: colors.muted, fontSize: 11, lineHeight: 17, marginTop: 10 }, issue: { color: colors.accent, fontSize: 12, lineHeight: 18, marginTop: 3 }, searchRow: { flexDirection: 'row', gap: 8 }, results: { gap: 8 }, result: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: colors.surface, borderRadius: 14, borderColor: colors.border, borderWidth: 1, padding: 10 }, thumb: { width: 38, height: 52, borderRadius: 7, alignItems: 'center', justifyContent: 'center' }, thumbText: { color: '#FFFFFFCC', fontWeight: '900', fontSize: 18 }, cardName: { color: colors.text, fontWeight: '900' }, cardMeta: { color: colors.muted, fontSize: 11, marginTop: 3 }, add: { color: colors.primary, fontSize: 25 }, counter: { flexDirection: 'row', alignItems: 'center', gap: 9 }, counterButton: { color: colors.primary, fontSize: 23, fontWeight: '900', padding: 5 }, quantity: { color: colors.text, fontWeight: '900', minWidth: 18, textAlign: 'center' }, empty: { color: colors.muted, textAlign: 'center', paddingVertical: 32 }, delete: { color: colors.danger, textAlign: 'center', fontWeight: '900', marginTop: spacing.xl, padding: 12 } });
