import { router, useLocalSearchParams } from 'expo-router';
import { useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { PrimaryButton, SearchInput } from '@/src/components/ui';
import { getCachedCard, searchCatalog } from '@/src/services/catalog';
import { useAppStore } from '@/src/store/AppStore';
import { colors, spacing } from '@/src/theme';
import { Card } from '@/src/types';

export default function DeckScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { decks, addCardToDeck, setDeckCardQuantity, removeDeck } = useAppStore(); const deck = decks.find((item) => item.id === id); const [query, setQuery] = useState(''); const [results, setResults] = useState<Card[]>([]); const [loading, setLoading] = useState(false);
  const total = deck?.cards.reduce((sum, item) => sum + item.quantity, 0) ?? 0; const resolved = useMemo(() => deck?.cards.map((item) => ({ ...item, card: getCachedCard(item.cardId) ?? item.cardSnapshot })).filter((item) => item.card) ?? [], [deck]);
  if (!deck) return <SafeAreaView style={styles.safe}><View style={styles.center}><Text style={styles.empty}>Deck não encontrado.</Text></View></SafeAreaView>;
  const search = async () => { setLoading(true); const response = await searchCatalog(deck.tcgId, query); setResults(response.cards); setLoading(false); };
  const destroy = () => { const action = () => { removeDeck(deck.id); router.back(); }; if (Platform.OS === 'web') { if (typeof window !== 'undefined' && window.confirm('Excluir este deck?')) action(); } else Alert.alert('Excluir deck?', 'Todas as cartas desta lista serão removidas.', [{ text: 'Cancelar', style: 'cancel' }, { text: 'Excluir', style: 'destructive', onPress: action }]); };
  return <SafeAreaView edges={['bottom']} style={styles.safe}><ScrollView contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled">
    <Text style={styles.title}>{deck.name}</Text><Text style={styles.meta}>{total} cartas · {deck.cards.length} diferentes</Text>
    <PrimaryButton label="Fotografar cartas (até 10)" onPress={() => router.push({ pathname: '/deck-scan/[id]', params: { id: deck.id } })} />
    <Text style={styles.section}>Adicionar pelo catálogo</Text><View style={styles.searchRow}><SearchInput value={query} onChangeText={setQuery} onSubmitEditing={search} placeholder="Nome da carta" style={{ flex: 1 }} /><PrimaryButton label="Buscar" onPress={search} /></View>
    {loading ? <ActivityIndicator color={colors.primary} style={{ margin: 24 }} /> : results.length > 0 && <View style={styles.results}>{results.slice(0, 12).map((card) => <Pressable key={card.id} onPress={() => addCardToDeck(deck.id, card)} style={styles.result}><View style={[styles.thumb, { backgroundColor: card.imageColor }]}><Text style={styles.thumbText}>{card.name[0]}</Text></View><View style={{ flex: 1 }}><Text style={styles.cardName}>{card.name}</Text><Text style={styles.cardMeta}>{card.set} · #{card.number}</Text></View><Text style={styles.add}>＋</Text></Pressable>)}</View>}
    <Text style={styles.section}>Lista do deck</Text>{resolved.length === 0 ? <Text style={styles.empty}>Busque cartas ou use a câmera para começar.</Text> : <View style={styles.results}>{resolved.map((item) => <View key={item.cardId} style={styles.result}><View style={[styles.thumb, { backgroundColor: item.card!.imageColor }]}><Text style={styles.thumbText}>{item.card!.name[0]}</Text></View><View style={{ flex: 1 }}><Text style={styles.cardName}>{item.card!.name}</Text><Text style={styles.cardMeta}>{item.card!.set}</Text></View><View style={styles.counter}><Pressable onPress={() => setDeckCardQuantity(deck.id, item.cardId, item.quantity - 1)}><Text style={styles.counterButton}>−</Text></Pressable><Text style={styles.quantity}>{item.quantity}</Text><Pressable onPress={() => setDeckCardQuantity(deck.id, item.cardId, item.quantity + 1)}><Text style={styles.counterButton}>＋</Text></Pressable></View></View>)}</View>}
    <Pressable onPress={destroy}><Text style={styles.delete}>Excluir deck</Text></Pressable>
  </ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, container: { padding: spacing.lg, paddingBottom: 48, gap: 12 }, center: { flex: 1, justifyContent: 'center' }, title: { color: colors.text, fontSize: 28, fontWeight: '900' }, meta: { color: colors.muted, marginBottom: 8 }, section: { color: colors.text, fontSize: 18, fontWeight: '900', marginTop: spacing.lg }, searchRow: { flexDirection: 'row', gap: 8 }, results: { gap: 8 }, result: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: colors.surface, borderRadius: 14, borderColor: colors.border, borderWidth: 1, padding: 10 }, thumb: { width: 38, height: 52, borderRadius: 7, alignItems: 'center', justifyContent: 'center' }, thumbText: { color: '#FFFFFFCC', fontWeight: '900', fontSize: 18 }, cardName: { color: colors.text, fontWeight: '900' }, cardMeta: { color: colors.muted, fontSize: 11, marginTop: 3 }, add: { color: colors.primary, fontSize: 25 }, counter: { flexDirection: 'row', alignItems: 'center', gap: 9 }, counterButton: { color: colors.primary, fontSize: 23, fontWeight: '900', padding: 5 }, quantity: { color: colors.text, fontWeight: '900', minWidth: 18, textAlign: 'center' }, empty: { color: colors.muted, textAlign: 'center', paddingVertical: 32 }, delete: { color: colors.danger, textAlign: 'center', fontWeight: '900', marginTop: spacing.xl, padding: 12 } });
